<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HeavyEquipmentSeeder extends Seeder
{
    public function run()
    {
        $equipments = [
            [
                'nomor_lambung' => 'EXCA-001',
                'name' => 'EXCAVATOR KOBELCO SK 200',
                'tahun' => 2004,
                'merek' => 'KOBELCO',
                'kondisi' => 'baik',
                'status' => 'ready',
                'location' => 'WORKSHOP KANTOR JL.AHMAD YANI KAV. I',
            ],
            [
                'nomor_lambung' => 'EXCA-002',
                'name' => 'EXCAVATOR AMPHIBIOUS ULTRATEX LONG ARM ZX200-5G',
                'tahun' => 2014,
                'merek' => 'HITACHI',
                'kondisi' => 'rusak_berat',
                'status' => 'maintenance',
                'location' => 'WORKSHOP KANTOR JL.AHMAD YANI KAV. I',
            ],
            [
                'nomor_lambung' => 'EXCA-003',
                'name' => 'EXCAVATOR LONG ARM ZX200LC-5G',
                'tahun' => 2014,
                'merek' => 'HITACHI',
                'kondisi' => 'baik',
                'status' => 'beroperasi',
                'location' => 'Pekerjaan Normalisasi Sungai Ciberes Desa Ciuya Kec. Waled Kab. Cirebon',
            ],
            [
                'nomor_lambung' => 'EXCA-004',
                'name' => 'EXCAVATOR HITACHI 120',
                'tahun' => 2014,
                'merek' => 'HITACHI',
                'kondisi' => 'baik',
                'status' => 'ready',
                'location' => 'WORKSHOP KANTOR JL.AHMAD YANI KAV. I',
            ],
            [
                'nomor_lambung' => 'EXCA-005',
                'name' => 'EXCAVATOR AMPHIBIOUS HITACHI MA 200 G',
                'tahun' => 2014,
                'merek' => 'HITACHI',
                'kondisi' => 'baik',
                'status' => 'ready',
                'location' => 'WORKSHOP KANTOR JL.AHMAD YANI KAV. I',
            ],
            [
                'nomor_lambung' => 'EXCA-006',
                'name' => 'EXCAVATOR AMPHIBIOUS AX110LR',
                'tahun' => 2015,
                'merek' => 'TAKEUCHI',
                'kondisi' => 'rusak_ringan',
                'status' => 'ready',
                'location' => 'WORKSHOP KANTOR JL.AHMAD YANI KAV. I',
            ],
            [
                'nomor_lambung' => 'EXCA-007',
                'name' => 'EXCAVATOR AMPHIBIOUS AX110LR',
                'tahun' => 2015,
                'merek' => 'TAKEUCHI',
                'kondisi' => 'rusak_ringan',
                'status' => 'ready',
                'location' => 'WORKSHOP KANTOR JL.AHMAD YANI KAV. I',
            ],
            [
                'nomor_lambung' => 'EXCA-008',
                'name' => 'EXCAVATOR AMPHIBIOUS AX80LR',
                'tahun' => 2015,
                'merek' => 'TAKEUCHI',
                'kondisi' => 'rusak_ringan',
                'status' => 'maintenance',
                'location' => 'WORKSHOP KANTOR JL.AHMAD YANI KAV. I',
            ],
            [
                'nomor_lambung' => 'EXCA-009',
                'name' => 'EXCAVATOR AMPHIBIOUS LONG ARM SUMITOMO SH.130.S',
                'tahun' => 2016,
                'merek' => 'SUMITOMO',
                'kondisi' => 'rusak_berat',
                'status' => 'maintenance',
                'location' => 'WORKSHOP KANTOR JL.AHMAD YANI KAV. I',
            ],
            [
                'nomor_lambung' => 'EXCA-010',
                'name' => 'EXCAVATOR PINDAD 200 (1)',
                'tahun' => 2018,
                'merek' => 'PINDAD',
                'kondisi' => 'baik',
                'status' => 'ready',
                'location' => 'WORKSHOP KANTOR JL.AHMAD YANI KAV. I',
            ],
            [
                'nomor_lambung' => 'EXCA-011',
                'name' => 'EXCAVATOR PINDAD 200 (2)',
                'tahun' => 2018,
                'merek' => 'PINDAD',
                'kondisi' => 'baik',
                'status' => 'ready',
                'location' => 'WORKSHOP KANTOR JL.AHMAD YANI KAV. I',
            ],
            [
                'nomor_lambung' => 'EXCA-012',
                'name' => 'EXCAVATOR AMPHIBIOUS DREGER PUMP',
                'tahun' => 2021,
                'merek' => 'KOMATSU',
                'kondisi' => 'baik',
                'status' => 'ready',
                'location' => 'WADUK MALAHAYU KAB. BREBES',
            ],
            [
                'nomor_lambung' => 'EXCA-013',
                'name' => 'EXCAVATOR PINDAD 55',
                'tahun' => 2022,
                'merek' => 'PINDAD',
                'kondisi' => 'baik',
                'status' => 'ready',
                'location' => 'WORKSHOP KANTOR JL.AHMAD YANI KAV. I',
            ],
            [
                'nomor_lambung' => 'EXCA-014',
                'name' => 'AMPHIBIOUS PINDAD EXCAVA 200',
                'tahun' => 2022,
                'merek' => 'PINDAD',
                'kondisi' => 'baik',
                'status' => 'ready',
                'location' => 'WORKSHOP KANTOR JL.AHMAD YANI KAV. I',
            ],
            [
                'nomor_lambung' => 'EXCA-015',
                'name' => 'EXCAVATOR ZAXIS 110MF-5G',
                'tahun' => 2024,
                'merek' => 'HITACHI',
                'kondisi' => 'baik',
                'status' => 'ready',
                'location' => 'WORKSHOP KANTOR JL.AHMAD YANI KAV. I',
            ],
            [
                'nomor_lambung' => 'CKT-001',
                'name' => 'ROUGH TERRAIN CRANE KATO SR300',
                'tahun' => 2014,
                'merek' => 'KATO',
                'kondisi' => 'baik',
                'status' => 'ready',
                'location' => 'WORKSHOP KANTOR JL.AHMAD YANI KAV. I',
            ],
            [
                'nomor_lambung' => 'FP-001',
                'name' => 'TRUCK MOBILE FLOOD PUMP 6 Inchi',
                'tahun' => 2017,
                'merek' => 'HINO',
                'kondisi' => 'baik',
                'status' => 'ready',
                'location' => 'KANTOR BBWS CIMANUK CISANGGARUNG JL. AHMAD YANI KAV . I',
            ],
            [
                'nomor_lambung' => 'POMP-001',
                'name' => 'POMPA AIR MODEL EO250B KAPASITAS 12 Inchi',
                'tahun' => 2010,
                'merek' => 'JOHNDEERE',
                'kondisi' => 'baik',
                'status' => 'ready',
                'location' => 'KANTOR BBWS CIMANUK CISANGGARUNG JL. AHMAD YANI KAV . I',
            ],
            [
                'nomor_lambung' => 'POMP-002',
                'name' => 'POMPA AIR MODEL EO250B KAPASITAS 12 Inchi',
                'tahun' => 2010,
                'merek' => 'JOHNDEERE',
                'kondisi' => 'baik',
                'status' => 'ready',
                'location' => 'WORKSHOP KANTOR JL.AHMAD YANI KAV. I',
            ],
            [
                'nomor_lambung' => 'EXCA-016',
                'name' => 'EXCAVATOR PINDAD 55',
                'tahun' => 2024,
                'merek' => 'PINDAD',
                'kondisi' => 'baik',
                'status' => 'ready',
                'location' => 'WORKSHOP KANTOR JL.AHMAD YANI KAV. I',
            ],
        ];

        foreach ($equipments as $equipment) {
            DB::table('heavy_equipments')->insert($equipment);
        }
    }
}
